apiVersion: batch/v1
kind: Job
metadata:
  name: sonataflow-db-migrator-job
spec:
  template:
    spec:
      containers:
        - name: sonataflow-db-migrator
          image: quay.io/rhkp/incubator-kie-kogito-service-db-migration-postgresql:latest
          command: ["/home/default/migration.sh"]
          env:
            - name: QUARKUS_DATASOURCE_DATAINDEX_JDBC_URL
              value: jdbc:postgresql://postgres:5432/sonataflow
            - name: QUARKUS_DATASOURCE_DATAINDEX_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: QUARKUS_DATASOURCE_DATAINDEX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: QUARKUS_DATASOURCE_JOBSSERVICE_JDBC_URL
              value: jdbc:postgresql://postgres:5432/sonataflow
            - name: QUARKUS_DATASOURCE_JOBSSERVICE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: QUARKUS_DATASOURCE_JOBSSERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: MIGRATE_DB_DATAINDEX
              value: "true"
            - name: MIGRATE_DB_JOBSSERVICE
              value: "true"
            - name: QUARKUS_FLYWAY_DATAINDEX_SCHEMAS
              value: di-schema
            - name: QUARKUS_FLYWAY_JOBSSERVICE_SCHEMAS
              value: js-schema
      restartPolicy: Never
  backoffLimit: 4