apiVersion: batch/v1
kind: Job
metadata:
  name: sonataflow-db-migrator-job
spec:
  template:
    spec:
      containers:
        - name: sonataflow-db-migrator
          image: quay.io/rhkp/incubator-kie-kogito-service-db-migration-postgresql:latest
          command: ["/home/default/migration.sh"]
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgres:5432/sonataflow
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: DI_DB_URL
              value: jdbc:postgresql://postgres:5432/sonataflow
            - name: DI_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: DI_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: JS_DB_URL
              value: jdbc:postgresql://postgres:5432/sonataflow
            - name: JS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: JS_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: MIGRATE_DATA_INDEX
              value: "true"
            - name: MIGRATE_JOBS_SERVICE
              value: "true"
            - name: DATA_INDEX_SCHEMA
              value: di-schema
            - name: JOBS_SERVICE_SCHEMA
              value: js-schema
      restartPolicy: Never
  backoffLimit: 4